name: Build Debian packages for the PineNote tweaks

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  # build_debs:
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v3

  #   - name: Install dependencies
  #     run: sudo apt -y update && sudo apt install build-essential devscripts debhelper-compat mkdocs mkdocs-material

  #   - name: Build
  #     run: ./build_all.sh

  #   - name: Artifacts
  #     uses: actions/upload-artifact@v3
  #     with:
  #       name: PineNote-Tweaks
  #       path: release/*

  build_debs:
    runs-on: ubuntu-latest
    name: Generate Debian packages for the Pinenote-tweaks
    steps:
      - name: Docker-based compilation
        id: compile-mesa-in-docker
        uses: PNDeb/pinenote-tweaks@main
      - name: Checkout rkbin
        run: |
          ls -l ${{ runner.temp }}/_github_home
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: pinenote-tweaks-debs
          path: ${{ runner.temp }}/_github_home/release

  # do_release:
  #   runs-on: ubuntu-latest
  #   needs:
  #     - build_debs
  #   steps:
  #     - name: Clone workflow repository
  #       uses: actions/checkout@v3
  #     - name: Download image artifacts
  #       uses: actions/download-artifact@v3
  #       with:
  #         path: artifacts/
  #     - name: Make release
  #       uses: softprops/action-gh-release@v0.1.15
  #       with:
  #         draft: true
  #         files: |
  #           artifacts/PineNote-Tweaks/*

  do_release:
    # if: startsWith(github.ref, 'refs/tags/')
    # if: contains(github.ref, "main")
    runs-on: ubuntu-latest
    needs:
      - build_debs
    steps:
      - name: Clone workflow repository
        uses: actions/checkout@v3
      - name: Download image artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts/
      - name: Make release
        uses: softprops/action-gh-release@v0.1.15
        with:
          draft: true
          files: |
            artifacts/pinenote-tweaks-debs/*
